import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "@/context/AuthContext";
import Header from "@/components/header/Header";
import QueryProvider from "@/service/client/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="inset-0 bg-zinc-200 fixed flex"></div>
				<div className="relative max-w-4xl mx-auto ">
					<AuthContext>
						<Header />
						{/* <ReduxProvider> */}
						<QueryProvider>
							<main>{children}</main>
						</QueryProvider>
						{/* </ReduxProvider> */}
					</AuthContext>
				</div>
			</body>
		</html>
	);
}
